In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import sklearn

In [3]:
datatrain = pd.read_csv('train.csv')
datatest = pd.read_csv('test.csv')
datatrain.shape

(31428, 27)

In [4]:
datatest.shape

(32086, 27)

In [5]:
datatrain.head(6)

label      id  visitTime  purchaseTime  hour          C1          C2  \
0     -1   61518   19297675            -1     6   928106152  2541203883   
1     -1  356604   19320277            -1    12  3382400190  2018710401   
2     -1  603441   19346318            -1    20  2569487005  2018710401   
3     -1  192754   19308171            -1     9  2569487005  2018710401   
4     -1  210892   19309442            -1     9  1659166197  2018710401   
5     -1  331463   19318283            -1    12   761728909  2018710401   

           C3          C4          C5  ...  N4  N5  N6  N7  N8  N9  N10  \
0  3606287998   306394936  2967512603  ...   0   0   0   0   0   0    0   
1  1302581498  2308170622  2967512603  ...   2   0   0   0   6   0    0   
2  4121075497  2210625817  2967512603  ...   0   0   0   0   0   0    0   
3  3531445293   652481754  2967512603  ...   0   0   0   0   0   0    0   
4  1047694444  2210625817  2967512603  ...   0   0   0   0   0   0    0   
5  3560336012  2210625817  2967512603  ...   0   0   0   0   0   0    0   

          C10         C11         C12  
0  1083418268  3831440054   830706566  
1  2993954402  2379633508  1284343215  
2  1601090997  3617851689  4220791646  
3  4114483006  3617851689  4220791646  
4  1971402551  2196958187   830706566  
5     4298464  3831440054  1213938795  

[6 rows x 27 columns]

In [6]:
datatest.head(6)

label     id  visitTime  purchaseTime  hour          C1          C2  \
0     -1  25540   19420446            -1    16  2569487005  2018710401   
1     -1  29938   19431062            -1    19  1981742921  1235983246   
2     -1   9585   19392956            -1     8  2486871669  1235983246   
3     -1  23597   19416124            -1    15  3427628467  1235983246   
4     -1  27695   19425109            -1    17  2214885086  2541203883   
5     -1   7641   19390814            -1     8   258125326   403381353   

           C3          C4          C5  ...  N4  N5  N6  N7  N8  N9  N10  \
0  1429850909  2308170622  2967512603  ...   0   0   0   0   0   0    0   
1  4203734567   652481754  2116767313  ...   0   0   0   0   0   0    0   
2  2776175989   652481754  2116767313  ...   0   0   0   0   0   0    0   
3  4172481347   652481754  2116767313  ...   0   0   0   0   0   0    0   
4  3948279888   652481754  2967512603  ...   0   0   0   0   0   0    0   
5   577069769   652481754  2967512603  ...   0   0   0   0   0   0    0   

          C10         C11         C12  
0  1887882016  3617851689  4220791646  
1  3375463994  2379633508  1284343215  
2  3441876061  2196958187  1550397227  
3  2835356425  3831440054  1213938795  
4  1453469701  3831440054   830706566  
5  2873164858  2379633508  1284343215  

[6 rows x 27 columns]

In [7]:
datatrain.columns

Index(['label', 'id', 'visitTime', 'purchaseTime', 'hour', 'C1', 'C2', 'C3',
       'C4', 'C5', 'C6', 'C7', 'C8', 'N1', 'C9', 'N2', 'N3', 'N4', 'N5', 'N6',
       'N7', 'N8', 'N9', 'N10', 'C10', 'C11', 'C12'],
      dtype='object')

In [8]:
datatest.columns

Index(['label', 'id', 'visitTime', 'purchaseTime', 'hour', 'C1', 'C2', 'C3',
       'C4', 'C5', 'C6', 'C7', 'C8', 'N1', 'C9', 'N2', 'N3', 'N4', 'N5', 'N6',
       'N7', 'N8', 'N9', 'N10', 'C10', 'C11', 'C12'],
      dtype='object')

In [9]:
datatrain.describe()

label             id     visitTime  purchaseTime          hour  \
count  31428.000000   31428.000000  3.142800e+04  3.142800e+04  31428.000000   
mean      -0.996373  321870.448835  1.931855e+07  3.504330e+04     11.799701   
std        0.085098  184665.780120  1.690395e+04  8.221503e+05      4.695434   
min       -1.000000      37.000000  1.927433e+07 -1.000000e+00      0.000000   
25%       -1.000000  162636.500000  1.930609e+07 -1.000000e+00      8.000000   
50%       -1.000000  322691.500000  1.931761e+07 -1.000000e+00     12.000000   
75%       -1.000000  481852.000000  1.933113e+07 -1.000000e+00     15.000000   
max        1.000000  638505.000000  1.936054e+07  1.935732e+07     23.000000   

                 C1            C2            C3            C4            C5  \
count  3.142800e+04  3.142800e+04  3.142800e+04  3.142800e+04  3.142800e+04   
mean   2.264373e+09  1.331820e+09  2.255368e+09  1.018468e+09  2.741699e+09   
std    1.077516e+09  7.900907e+08  1.125852e+09  7.260969e+08  3.771211e+08   
min    7.942600e+04  4.033814e+08  5.538985e+06  3.063949e+08  2.116767e+09   
25%    1.464958e+09  4.033814e+08  1.408383e+09  6.524818e+08  2.116767e+09   
50%    2.569487e+09  1.235983e+09  2.243934e+09  6.524818e+08  2.967513e+09   
75%    2.834768e+09  2.018710e+09  3.326547e+09  6.524818e+08  2.967513e+09   
max    4.294924e+09  2.541204e+09  4.292704e+09  2.308171e+09  3.955179e+09   

       ...            N4            N5            N6            N7  \
count  ...  31428.000000  31428.000000  31428.000000  31428.000000   
mean   ...      0.134307      0.002386      0.027269      0.002164   
std    ...      1.258795      0.156001      0.562668      0.079745   
min    ...      0.000000      0.000000      0.000000      0.000000   
25%    ...      0.000000      0.000000      0.000000      0.000000   
50%    ...      0.000000      0.000000      0.000000      0.000000   
75%    ...      0.000000      0.000000      0.000000      0.000000   
max    ...     20.000000     20.000000     20.000000     10.000000   

                 N8            N9           N10           C10           C11  \
count  31428.000000  31428.000000  31428.000000  3.142800e+04  3.142800e+04   
mean       0.415680      0.042319      0.057560  2.218926e+09  2.939366e+09   
std        3.184785      1.008314      1.158253  1.235285e+09  1.020598e+09   
min        0.000000      0.000000      0.000000  1.626600e+04  4.393702e+07   
25%        0.000000      0.000000      0.000000  1.140301e+09  2.379634e+09   
50%        0.000000      0.000000      0.000000  2.274128e+09  3.617852e+09   
75%        0.000000      0.000000      0.000000  3.376114e+09  3.831440e+09   
max       97.000000     85.000000     86.000000  4.294964e+09  3.831440e+09   

                C12  
count  3.142800e+04  
mean   2.158890e+09  
std    1.416777e+09  
min    2.456084e+08  
25%    1.213939e+09  
50%    1.284343e+09  
75%    4.220792e+09  
max    4.220792e+09  

[8 rows x 27 columns]

In [10]:
datatest.describe()

label            id     visitTime  purchaseTime          hour  \
count  32086.0  32086.000000  3.208600e+04       32086.0  32086.000000   
mean      -1.0  16043.500000  1.940351e+07          -1.0     11.398928   
std        0.0   9262.574705  1.737842e+04           0.0      4.824402   
min       -1.0      1.000000  1.936073e+07          -1.0      0.000000   
25%       -1.0   8022.250000  1.939124e+07          -1.0      8.000000   
50%       -1.0  16043.500000  1.940027e+07          -1.0     10.000000   
75%       -1.0  24064.750000  1.941714e+07          -1.0     15.000000   
max       -1.0  32086.000000  1.944696e+07          -1.0     23.000000   

                 C1            C2            C3            C4            C5  \
count  3.208600e+04  3.208600e+04  3.208600e+04  3.208600e+04  3.208600e+04   
mean   2.270514e+09  1.248835e+09  2.238694e+09  9.961022e+08  2.750413e+09   
std    1.070761e+09  7.880539e+08  1.136736e+09  7.031734e+08  3.746974e+08   
min    1.045850e+05  4.033814e+08  8.111500e+04  3.063949e+08  2.116767e+09   
25%    1.498136e+09  4.033814e+08  1.350443e+09  6.524818e+08  2.116767e+09   
50%    2.569487e+09  1.235983e+09  2.118681e+09  6.524818e+08  2.967513e+09   
75%    2.823486e+09  2.018710e+09  3.348226e+09  6.524818e+08  2.967513e+09   
max    4.294964e+09  2.541204e+09  4.291934e+09  2.308171e+09  3.955179e+09   

       ...            N4            N5            N6            N7  \
count  ...  32086.000000  32086.000000  32086.000000  32086.000000   
mean   ...      0.123294      0.001776      0.026180      0.002369   
std    ...      1.205905      0.131982      0.554355      0.073604   
min    ...      0.000000      0.000000      0.000000      0.000000   
25%    ...      0.000000      0.000000      0.000000      0.000000   
50%    ...      0.000000      0.000000      0.000000      0.000000   
75%    ...      0.000000      0.000000      0.000000      0.000000   
max    ...     20.000000     20.000000     20.000000      6.000000   

                 N8            N9           N10           C10           C11  \
count  32086.000000  32086.000000  32086.000000  3.208600e+04  3.208600e+04   
mean       0.361996      0.021193      0.028112  2.203086e+09  2.946493e+09   
std        2.831414      0.627150      0.669946  1.240951e+09  9.985179e+08   
min        0.000000      0.000000      0.000000  2.408980e+05  5.877978e+07   
25%        0.000000      0.000000      0.000000  1.124277e+09  2.379634e+09   
50%        0.000000      0.000000      0.000000  2.256731e+09  3.617852e+09   
75%        0.000000      0.000000      0.000000  3.341150e+09  3.831440e+09   
max       97.000000     46.000000     46.000000  4.294786e+09  4.166090e+09   

                C12  
count  3.208600e+04  
mean   2.175229e+09  
std    1.418685e+09  
min    2.456084e+08  
25%    1.213939e+09  
50%    1.284343e+09  
75%    4.220792e+09  
max    4.220792e+09  

[8 rows x 27 columns]

In [11]:
len(datatrain[datatrain['label']==1])

57

In [12]:
len(datatrain[datatrain['label']==-1])

31371

In [13]:
#missing values
datatrain.isnull().sum()

label           0
id              0
visitTime       0
purchaseTime    0
hour            0
C1              0
C2              0
C3              0
C4              0
C5              0
C6              0
C7              0
C8              0
N1              0
C9              0
N2              0
N3              0
N4              0
N5              0
N6              0
N7              0
N8              0
N9              0
N10             0
C10             0
C11             0
C12             0
dtype: int64

In [14]:
datatest.isnull().sum()

label           0
id              0
visitTime       0
purchaseTime    0
hour            0
C1              0
C2              0
C3              0
C4              0
C5              0
C6              0
C7              0
C8              0
N1              0
C9              0
N2              0
N3              0
N4              0
N5              0
N6              0
N7              0
N8              0
N9              0
N10             0
C10             0
C11             0
C12             0
dtype: int64

In [15]:
#purchaseTime only happens when there is a purchase, so we eliminate the feature.
datatrain = datatrain.drop(['purchaseTime', 'id'], axis = 1)
datatrain.columns

Index(['label', 'visitTime', 'hour', 'C1', 'C2', 'C3', 'C4', 'C5', 'C6', 'C7',
       'C8', 'N1', 'C9', 'N2', 'N3', 'N4', 'N5', 'N6', 'N7', 'N8', 'N9', 'N10',
       'C10', 'C11', 'C12'],
      dtype='object')

In [16]:
datatest = datatest.drop(['label','purchaseTime', 'id'], axis = 1)
datatest.columns

Index(['visitTime', 'hour', 'C1', 'C2', 'C3', 'C4', 'C5', 'C6', 'C7', 'C8',
       'N1', 'C9', 'N2', 'N3', 'N4', 'N5', 'N6', 'N7', 'N8', 'N9', 'N10',
       'C10', 'C11', 'C12'],
      dtype='object')

In [17]:
#replace the -1 of labels to 0
datatrain = datatrain.replace(-1,0)
datatest = datatest.replace(-1,0)

In [18]:
# Separating the  input features (X) and target variable (y)
X = datatrain.drop('label', axis = 1)
y = datatrain['label']

In [19]:
from sklearn.model_selection import train_test_split
# split your dataset into training & test parts, X
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=42)

In [28]:
from imblearn.over_sampling import SMOTE

X_temp, y_temp = SMOTE(random_state=42).fit_resample(X_train, y_train)

X_train, X_test, y_train, y_test = train_test_split(X_temp, y_temp)

print(f'''Shape of X before SMOTE: {X.shape}
Shape of X after SMOTE: {X_temp.shape}''')

print('\nBalance of classes in percentage:')
y_temp.value_counts(normalize=True) * 100

Shape of X before SMOTE: (31428, 24)
Shape of X after SMOTE: (7968, 24)

Balance of classes in percentage:


1    50.0
0    50.0
Name: label, dtype: float64

In [29]:
from sklearn.linear_model import LogisticRegression
logmodel = LogisticRegression(random_state=42)
logmodel.fit(X_train,y_train)

LogisticRegression(random_state=42)

In [30]:
predictions = logmodel.predict(X_test)
from sklearn.metrics import classification_report
print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

           0       0.75      0.77      0.76       988
           1       0.76      0.75      0.75      1004

    accuracy                           0.76      1992
   macro avg       0.76      0.76      0.76      1992
weighted avg       0.76      0.76      0.76      1992



In [31]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, predictions)

array([[757, 231],
       [256, 748]])

In [32]:
test_score = logmodel.score(X_test, y_test)
print("model score: %.3f " % test_score)

model score: 0.756 


In [33]:
y_pred = logmodel.predict(datatest)
print(y_pred)

[0 0 0 ... 0 0 0]


In [34]:
probability = logmodel.predict_proba(datatest)[:,1]
print(probability)

[0.09863905 0.11583037 0.19772559 ... 0.20522994 0.3727097  0.49619237]


In [35]:
data_test = pd.read_csv('test.csv')
result = pd.DataFrame({'id': data_test.id, 'Label' : probability})
result

id     Label
0      25540  0.098639
1      29938  0.115830
2       9585  0.197726
3      23597  0.277840
4      27695  0.802439
...      ...       ...
32081  25657  0.359657
32082   6384  0.304462
32083  26582  0.205230
32084   5394  0.372710
32085  26787  0.496192

[32086 rows x 2 columns]

In [36]:
result.to_csv('/Users/henrykettaneh/ESCP - Big Data/Term 2 Classes/Machine Learning with Python/A4_5/Results.csv', index=False)